/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include"stm32f103c6.h"
#include"stm32_f103c6_gpio_driver.h"
#include"stm32_f103c6_EXTI_driver.h"
#include "lcd.h"


uint8_t IRQ_Flag = 0;
void clock_init(){
	RCC_GPIOA_CLK_EN();  /* to enable clock for GPIOA */
	RCC_GPIOB_CLK_EN();  /* to enable clock for GPIOB */
	RCC_AFIO_CLK_EN();   /* to enable clock for AFIO  */
}

void EXTI9_Callback(void)
{
	IRQ_Flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 is Happened");
	delay_ms(1000);
}


int main(void)
{
	clock_init();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.IRQ_EN= EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1;

	/* Loop forever */
	for(;;)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag=0;
		}
	}
}
