/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"stm32f103c6.h"
#include"stm32_f103c6_gpio_driver.h"
#include "stm32_f103c6_USART_driver.h"
#include "lcd.h"

void clock_init(){
	RCC_GPIOA_CLK_EN();  /* to enable clock for GPIOA */
	RCC_GPIOB_CLK_EN();  /* to enable clock for GPIOB */
	RCC_GPIOC_CLK_EN();  /* to enable clock for GPIOC */
	RCC_AFIO_CLK_EN();   /* to enable clock for AFIO  */
}
void GPIO_init(){

	GPIO_PinConfig_t pincfg;
	// PA1 floating input
	pincfg.GPIO_PinNumber= GPIO_PIN_2;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA , &pincfg);

	pincfg.GPIO_PinNumber= GPIO_PIN_5;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA , &pincfg);

}
void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0; i<time; i++)
		for(j=0;j<255;j++);
}

volatile uint8_t  ch= '\0';
void UART_IRQ_callback(void)
{
	MCAL_UART_ReceiveData(USART1, &ch ,disable );
	if(ch == 0xfd )
	{
		MCAL_GPIO_TogglePin (  GPIOA, GPIO_PIN_2 );
		wait_ms(1000);
		MCAL_GPIO_TogglePin (  GPIOA, GPIO_PIN_2 );
		wait_ms(1000);
	}
	else if(ch == 0xfa)
	{
		MCAL_GPIO_TogglePin (  GPIOA, GPIO_PIN_5 );
		wait_ms(1000);
		MCAL_GPIO_TogglePin (  GPIOA, GPIO_PIN_5 );
		wait_ms(1000);
	}
	ch= '\0';

}
int main(void)
{
	UART_Config uartcfg;
	clock_init();
	LCD_INIT();
	GPIO_init();
	uartcfg.BaudRate = UART_BaudRate_115200;
	uartcfg.HwFlowCtl= UART_HwFlowCtl_NONE;
	//uartcfg.IRQ_Enable = UART_IRQ_Enable_NONE;
	uartcfg.IRQ_Enable =UART_IRQ_Enable_RXNEIE;
	uartcfg.P_IRQ_CallBack= &UART_IRQ_callback;
	//uartcfg.P_IRQ_CallBack=NULL;
	uartcfg.Parity = UART_Parity__NONE;
	uartcfg.Payload_Length =UART_Payload_Length_8B;
	uartcfg.StopBits =UART_StopBits__1;
	uartcfg.USART_Mode=UART_MODE_RX;

	MCAL_UART_GPIO_Set_Pins(USART1);
	MCAL_UART_Init(USART1, &uartcfg);

	while(1)
	{

	}

}


