/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"stm32f103c6.h"
#include"stm32_f103c6_gpio_driver.h"

void clock_init(){
	RCC_GPIOA_CLK_EN(); /* to enable clock for GPIOA */
	RCC_GPIOB_CLK_EN();     /* to enable clock for GPIOB */
}
void GPIO_init(){

	GPIO_PinConfig_t pincfg;
	// PA1 floating input
	pincfg.GPIO_PinNumber= GPIO_PIN_1;
	pincfg.GPIO_MODE =GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA , &pincfg);

	// PB1 output push pull, speed 10MHz
	pincfg.GPIO_PinNumber= GPIO_PIN_1;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_Output_Speed =GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &pincfg);

	// PA13 floating input
	pincfg.GPIO_PinNumber= GPIO_PIN_13;
	pincfg.GPIO_MODE =GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA , &pincfg);

	// PB13 output push pull, speed 10MHz
	pincfg.GPIO_PinNumber= GPIO_PIN_13;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_Output_Speed =GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &pincfg);

}
void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0; i<time; i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		//PA1 >>> Connected external PUR
		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) // press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 );
		}
		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		wait_ms(1);

	}

}
