/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Terminal<----->USART1 : MSU1 : (SPI1 Master) ---> (SPI2 Slave) : MCU2: USART2 ---> Terminal2
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_Act_As_Master
#define MCU_Act_As_Slave

#include"stm32f103c6.h"
#include"stm32_f103c6_gpio_driver.h"
#include"stm32_f103c6_USART_driver.h"
#include"stm32_f103c6_SPI_driver.h"

unsigned char ch;

void clock_init(){
	RCC_GPIOA_CLK_EN();  /* to enable clock for GPIOA */
	RCC_GPIOB_CLK_EN();  /* to enable clock for GPIOB */
	RCC_AFIO_CLK_EN();   /* to enable clock for AFIO  */
}

void SPI1_IRQ_callback(struct S_IRQ_SRC irq_scr )
{

#ifdef MCU_Act_As_Slave
	if(irq_scr.RXNE)
	{
		ch=0xf;
		MCAL_SPI_TX_RX(SPI1,&ch, PollingDisable);
		MCAL_UART_SendData(USART1, &ch, enable);
	}
#endif

}

void UART_IRQ_callback(void)
{

#ifdef MCU_Act_As_Master
	MCAL_UART_ReceiveData(USART1, &ch ,disable );
	MCAL_UART_SendData(USART1, &ch, enable);
	// send to SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);
	MCAL_SPI_TX_RX(SPI1, &ch, PollingEnable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
#endif

}

int main(void)
{
	UART_Config uartcfg;
	SPI_Config  SPI1cfg;
	clock_init();
	/************** UART Init *****************/
	uartcfg.BaudRate = UART_BaudRate_115200;
	uartcfg.HwFlowCtl= UART_HwFlowCtl_NONE;
	//uartcfg.IRQ_Enable = UART_IRQ_Enable_NONE;
	uartcfg.IRQ_Enable =UART_IRQ_Enable_RXNEIE;
	uartcfg.P_IRQ_CallBack= &UART_IRQ_callback;
	//uartcfg.P_IRQ_CallBack=NULL;
	uartcfg.Parity = UART_Parity__NONE;
	uartcfg.Payload_Length =UART_Payload_Length_8B;
	uartcfg.StopBits =UART_StopBits__1;
	uartcfg.USART_Mode=UART_MODE_RX;

	MCAL_UART_GPIO_Set_Pins(USART1);
	MCAL_UART_Init(USART1, &uartcfg);

	/********** SPI Init **************/
	// Common configuration
	SPI1cfg.CLKPhase =SPI_Clock_Phase_2EDGE_first_data_capture_edge ;
	SPI1cfg.CLKPolarity= SPI_CLKPolarity_HIGH_when_idle;
	SPI1cfg.DataSize = SPI_DataSize_8BIT ;
	SPI1cfg.Frame_Format=SPI_Frame_Format_MSB_transmited_first;
	// assume by default pclk2 = 8MHz
	SPI1cfg.SPI_BAUDRATEPRESCALER=SPI_BAUDRATEPRESCALER_8;
	SPI1cfg.Communication_Mode = SPI_DIRECTIONAL_2LINES;
#ifdef MCU_Act_As_Master
	SPI1cfg.Device_Mode=SPI_Device_Mode_MASTER;
	SPI1cfg.IRQ_Enable = SPI_IRQ_Enable_NONE;
	SPI1cfg.NSS =SPI_NSS_soft_NSSInternalsoft_set;
	SPI1cfg.P_IRQ_CallBack = NULL;

	//configure SS on portApin4 by GPIO

	GPIO_PinConfig_t pincfg;
	// PA4 floating input
	pincfg.GPIO_PinNumber= GPIO_PIN_4;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA , &pincfg);
	// force the slave select (high) idle Mode
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);

#endif

#ifdef MCU_Act_As_Slave
	SPI1cfg.Device_Mode=SPI_Device_Mode_SLAVE;
	SPI1cfg.IRQ_Enable = SPI_IRQ_Enable_RXNEIE;
	SPI1cfg.NSS =SPI_NSS_Hard_Slave;
	SPI1cfg.P_IRQ_CallBack = SPI1_IRQ_callback;
#endif


	MCAL_SPI_Init(SPI1, &SPI1cfg);
	MCAL_SPI_GPIO_Set_Pins(SPI1);



	while(1)
	{

	}

}


